### ISSUE TITLE
Questions about inference time

### ISSUE THREAD

**Issue by yeontaek** [THUDM/P-tuning-v2#17]
Hi. I have a question.

In the case of Prefix Tuning, I think there will be some advantages in learning time.

However, I don't think there will be a big advantage in the inference time of the learned model, so what do you think?

**Comment by Xiao9905** [comment]
Thanks for your comment. Yes, the significant bottleneck of big model inference speed lies in the transformer part rather than the soft prompts. We discover that P-tuning v2 mainly needs less than 20 soft tokens for NLU tasks in SuperGLUE, which actually takes very little more time in the inference.

**Comment by yeontaek** [comment]
Thank you for your quick answer :)

Should it be understood that the advantage of P-tuning v2 is that it can produce performance similar to Fine-tuning with fewer learning parameters?

**Comment by Xiao9905** [comment]
The advantages of P-tuning v2 mainly lies in 3 aspects:
1) It produces comparable performance to fine-tuning with fewer parameters, and across a range of model scales (from 330M to 10B)
2) It proves its efficiency in harder sequence tasks including NER, MRC and SRL
3) It shows the use of multitask task training of prompts can encourage task transferability

**Comment by yeontaek** [comment]
Thank you :)
